'use client'
import React, { useState } from 'react';
import { FiSearch, FiRefreshCw, FiGlobe, FiTwitter, FiFacebook, FiChevronDown, FiChevronUp, FiCheck, FiZap, FiImage } from 'react-icons/fi';
import axios from 'axios';
import { getStorage } from '../lib/storage';

const API_URI = process.env.NEXT_PUBLIC_API_URI || 'http://localhost:3000';
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://belorella.com';

const SEOEditor = ({ seo, onChange, type = 'product', itemId, itemName, variantId, label, onRegenerated }) => {
  const [expanded, setExpanded] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState('google');

  const handleFieldChange = (field, value) => {
    // Mark as manually edited so automatic regeneration never clobbers it
    onChange({ ...seo, [field]: value, autoGenerated: false });
  };

  const handleAutoGenerate = async () => {
    if (!itemId) return;
    setGenerating(true);
    try {
      let endpoint;
      if (type === 'blog') endpoint = `/api/seo/blog/${itemId}`;
      else if (type === 'variant') endpoint = `/api/seo/product/${itemId}/variant/${variantId}`;
      else endpoint = `/api/seo/product/${itemId}`;
      const res = await axios.post(`${API_URI}${endpoint}`, {}, {
        headers: { Authorization: `Bearer ${getStorage('adminAccessToken')}` }
      });
      if (res.data.seo) {
        onChange(res.data.seo);
        if (onRegenerated) onRegenerated(res.data.seo);
      }
    } catch (err) {
      console.error('SEO generation failed:', err);
      alert(err.response?.data?.message || 'SEO generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const titleLength = (seo.metaTitle || '').length;
  const descLength = (seo.metaDescription || '').length;
  const displayTitle = seo.metaTitle || itemName || 'Page Title';
  const displayDesc = seo.metaDescription || 'No description set. Add a meta description for better search visibility.';
  const displayUrl = type === 'blog'
    ? `${SITE_URL}/blog/${itemName || 'post'}`
    : type === 'variant'
      ? `${SITE_URL}/products/${itemId || 'product'}?variant=${variantId || ''}`
      : `${SITE_URL}/products/${itemName || 'product'}`;

  return (
    <div className="border border-cool-gray overflow-hidden">
      <button
        type="button"
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-4 py-3 bg-maybelline-pink/10 hover:bg-maybelline-pink/20 transition text-black"
      >
        <span className="flex items-center gap-2 font-heading text-lg" style={{ fontFamily: "'Inter', serif" }}>
          <FiSearch size={18} className="text-maybelline-pink" />
          {label || 'SEO Settings'}
          {seo.metaTitle && <FiCheck size={14} className="text-green-500" />}
        </span>
        {expanded ? <FiChevronUp size={20} className="text-maybelline-pink" /> : <FiChevronDown size={20} className="text-maybelline-pink" />}
      </button>

      {expanded && (
        <div className="p-4 space-y-4">
          {/* Auto Generate Button */}
          <div className="flex items-center gap-2 mb-4">
            <button
              type="button"
              onClick={handleAutoGenerate}
              disabled={generating || !itemId}
              className="flex items-center gap-2 px-4 py-2 bg-maybelline-pink text-white text-sm font-semibold hover:bg-maybelline-magenta transition disabled:opacity-50"
            >
              {generating ? <FiRefreshCw size={14} className="animate-spin" /> : <FiZap size={14} />}
              {generating ? 'Generating...' : 'Auto-Generate SEO'}
            </button>
            {seo.autoGenerated && (
              <span className="text-xs text-mid-gray bg-maybelline-light px-2 py-1 rounded">Auto-generated</span>
            )}
            {seo.lastGenerated && (
              <span className="text-xs text-mid-gray">Last: {new Date(seo.lastGenerated).toLocaleDateString()}</span>
            )}
          </div>

          {/* Fields */}
          <div>
            <label className="block mb-1 text-sm font-medium text-dark-gray">
              Meta Title <span className={titleLength > 60 ? 'text-red-500' : 'text-mid-gray'}>({titleLength}/60)</span>
            </label>
            <input
              type="text"
              value={seo.metaTitle || ''}
              onChange={(e) => handleFieldChange('metaTitle', e.target.value)}
              maxLength={70}
              placeholder="SEO title for search engines"
              className="w-full px-4 py-3 border border-cool-gray bg-white text-black focus:outline-none focus:ring-2 focus:ring-maybelline-pink"
            />
          </div>

          <div>
            <label className="block mb-1 text-sm font-medium text-dark-gray">
              Meta Description <span className={descLength > 155 ? 'text-red-500' : 'text-mid-gray'}>({descLength}/160)</span>
            </label>
            <textarea
              value={seo.metaDescription || ''}
              onChange={(e) => handleFieldChange('metaDescription', e.target.value)}
              maxLength={170}
              rows={3}
              placeholder="Brief description for search engine results"
              className="w-full px-4 py-3 border border-cool-gray bg-white text-black focus:outline-none focus:ring-2 focus:ring-maybelline-pink"
            />
          </div>

          <div>
            <label className="block mb-1 text-sm font-medium text-dark-gray">Meta Keywords</label>
            <input
              type="text"
              value={seo.metaKeywords || ''}
              onChange={(e) => handleFieldChange('metaKeywords', e.target.value)}
              placeholder="Comma-separated keywords (e.g. dress, fashion, summer)"
              className="w-full px-4 py-3 border border-cool-gray bg-white text-black focus:outline-none focus:ring-2 focus:ring-maybelline-pink"
            />
          </div>

          <div>
            <label className="block mb-1 text-sm font-medium text-dark-gray">OG Image URL</label>
            <input
              type="text"
              value={seo.ogImage || ''}
              onChange={(e) => handleFieldChange('ogImage', e.target.value)}
              placeholder="URL for social media share image"
              className="w-full px-4 py-3 border border-cool-gray bg-white text-black focus:outline-none focus:ring-2 focus:ring-maybelline-pink"
            />
            {seo.ogImage && (
              <div className="mt-2">
                <img src={seo.ogImage} alt="OG Preview" className="w-full max-h-40 object-cover border border-cool-gray rounded" />
              </div>
            )}
          </div>

          {/* Live Previews */}
          <div className="border-t border-cool-gray pt-4">
            <div className="flex gap-2 mb-3">
              <button type="button" onClick={() => setActiveTab('google')}
                className={`flex items-center gap-1 px-3 py-1.5 text-xs font-semibold rounded transition ${activeTab === 'google' ? 'bg-maybelline-pink text-white' : 'bg-cool-gray text-dark-gray hover:bg-mid-gray'}`}>
                <FiSearch size={12} /> Google
              </button>
              <button type="button" onClick={() => setActiveTab('facebook')}
                className={`flex items-center gap-1 px-3 py-1.5 text-xs font-semibold rounded transition ${activeTab === 'facebook' ? 'bg-[#1877F2] text-white' : 'bg-cool-gray text-dark-gray hover:bg-mid-gray'}`}>
                <FiFacebook size={12} /> Facebook
              </button>
              <button type="button" onClick={() => setActiveTab('twitter')}
                className={`flex items-center gap-1 px-3 py-1.5 text-xs font-semibold rounded transition ${activeTab === 'twitter' ? 'bg-[#1DA1F2] text-white' : 'bg-cool-gray text-dark-gray hover:bg-mid-gray'}`}>
                <FiTwitter size={12} /> Twitter
              </button>
            </div>

            {/* Google SERP Preview */}
            {activeTab === 'google' && (
              <div className="bg-white border border-cool-gray p-4 rounded">
                <p className="text-[#202124] text-lg font-normal leading-snug truncate" style={{ fontFamily: 'Arial, sans-serif' }}>
                  {displayTitle}
                </p>
                <p className="text-[#4d5156] text-sm mt-1 leading-snug" style={{ fontFamily: 'Arial, sans-serif' }}>
                  {displayDesc.slice(0, 155)}{displayDesc.length > 155 ? '...' : ''}
                </p>
                <p className="text-[#202124] text-sm mt-1" style={{ fontFamily: 'Arial, sans-serif' }}>
                  <span className="text-[#70757a]">{displayUrl}</span>
                </p>
                <div className="mt-2 flex gap-4">
                  {titleLength > 60 && <span className="text-xs text-red-500">Title too long ({titleLength}/60)</span>}
                  {descLength > 155 && <span className="text-xs text-red-500">Description too long ({descLength}/155)</span>}
                  {titleLength <= 60 && titleLength > 0 && <span className="text-xs text-green-600">Title length OK</span>}
                  {descLength <= 155 && descLength > 0 && <span className="text-xs text-green-600">Description OK</span>}
                </div>
              </div>
            )}

            {/* Facebook Preview */}
            {activeTab === 'facebook' && (
              <div className="bg-[#f0f2f5] border border-cool-gray rounded overflow-hidden">
                {seo.ogImage && (
                  <img src={seo.ogImage} alt="OG" className="w-full h-48 object-cover" />
                )}
                <div className="p-3 bg-white border-t border-cool-gray">
                  <p className="text-[#65676b] text-xs uppercase">{displayUrl.replace(/https?:\/\//, '').split('/')[0]}</p>
                  <p className="text-[#1c1e21] text-base font-semibold mt-0.5 truncate">{displayTitle}</p>
                  <p className="text-[#65676b] text-sm mt-0.5 line-clamp-2">{displayDesc.slice(0, 110)}</p>
                </div>
              </div>
            )}

            {/* Twitter Preview */}
            {activeTab === 'twitter' && (
              <div className="bg-[#15202b] border border-[#38444d] rounded overflow-hidden">
                {seo.ogImage && (
                  <img src={seo.ogImage} alt="OG" className="w-full h-48 object-cover" />
                )}
                <div className="p-3 bg-[#192734] border-t border-[#38444d]">
                  <p className="text-[#8b98a5] text-xs">{displayUrl.replace(/https?:\/\//, '').split('/')[0]}</p>
                  <p className="text-[#e7e9ea] text-base font-semibold mt-0.5 truncate">{displayTitle}</p>
                  <p className="text-[#8b98a5] text-sm mt-0.5 line-clamp-2">{displayDesc.slice(0, 120)}</p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default SEOEditor;
